### PR TITLE
Development

### PR DESCRIPTION
**Pull request by uhufa**

### CODE REVIEW

**Comment by Piiit** [comment]
@uhufa the CI fails... could you please have a look at https://ci.opendatahub.bz.it/job/it.bz.opendatahub.web-component-store/job/PR-43/1/console 

```
yarn install v1.12.3
info No lockfile found.
[1/4] Resolving packages...
warning nuxt > @nuxt/webpack > @nuxt/babel-preset-app > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning odh-web-components-configurator > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning vue-jest > babel-plugin-transform-es2015-modules-commonjs > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
error semver@7.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.15.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Thank you

**Comment by Piiit** [comment]
@uhufa Do I need to install node 10 for this now?

**Comment by uhufa** [comment]
> @uhufa Do I need to install node 10 for this now?

I am already looking into the matter. I did not change anything as far as requirements are concerned. I guess some node-dependency got an update that is not compatible. I'll need to find it and lock it to a version that works.

**Comment by uhufa** [comment]
looks good now

**Pull request merged**
